-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://gitlab.com/pycqa/flake8
    rev: 'master'
    hooks:
    -  id: flake8
       additional_dependencies: [flake8-docstrings]
#-   repo: https://github.com/pre-commit/mirrors-pylint
#    rev: 'master'
#    hooks:
#    -   id: pylint
