version: '2'
services:
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0'
        environment:
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ulimits:
            nproc: 65535
            memlock:
                soft: -1
                hard: -1
        cap_add:
            - ALL
        privileged: true
        ports:
            - '9200:9200'
        volumes:
          - elasticsearch:/usr/share/elasticsearch/data

    rabbitmq:
        image: 'rabbitmq:3-alpine'
        ports:
            - '5672:5672'

    aleph_base:
        user: aleph
        build: .

    aleph_collector:
        extends: aleph_base
        command: celery worker -l info -A aleph -c 1 -Q collector -n collector@%h
        links:
            - elasticsearch
            - rabbitmq
        depends_on:
            - elasticsearch
            - rabbitmq
        volumes:
            - ./samples:/opt/aleph/samples

    aleph_worker:
        extends: aleph_base
        command: celery worker -l info -A aleph -c 2 -Q manager,store -n worker@%h
        links:
            - elasticsearch
            - rabbitmq
        depends_on:
            - elasticsearch
            - rabbitmq

    aleph_plugins_generic:
        extends: aleph_base
        command: celery worker -l info -A aleph -c 5 -Q plugins.generic -n plugins_generic@%h
        links:
            - elasticsearch
            - rabbitmq
        depends_on:
            - elasticsearch
            - rabbitmq

    aleph_plugins_sandbox:
        extends: aleph_base
        command: celery worker -l info -A aleph -c 2 -Q plugins.sandbox -n plugins_sandbox@%h
        links:
            - elasticsearch
            - rabbitmq
        depends_on:
            - elasticsearch
            - rabbitmq
    
    aleph_beat:
        extends: aleph_base
        command: celery beat -A aleph
        links:
            - elasticsearch
            - rabbitmq
        depends_on:
            - elasticsearch
            - rabbitmq
            - aleph_collector
volumes:
    elasticsearch:
        driver: local
